#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Check if a given number is prime or not

Created on Sun Aug  9 16:20:55 2020

@author: Abin
"""

num = int(input("Enter a positive integer: "))

if num < 1:
    print("Not a prime number")
else:
    for i in range(2, (num//2 + 1)):
        if num % i == 0:
            print("Not a prime number")
            break
    else:
        print("Prime Number")